theme: jekyll-theme-cayman
title: 国連 GGIM 防災会議 2020 / UN-GGIM WG-Disasters Conference 2020
description: hosted by Geospatial Information Authority of Japan (GSI), United Nations Committee of Experts for Global Geospatial Information Management (UN-GGIM) WG-Disasters, Regional Committee of UN-GGIM for Asia and the Pacific (UN-GGIM-AP), and Japan International Cooperation Agency (JICA)
